# 배열의 생성과 변형
## 넘파이 배열
  - 배열을 사용하면 적은 메모리로 많은 데이터 빠르게 처리
  - 배열 : 모든 원소가 같은 자료형, 원소의 갯수를 바꿀 수 없다.
  - 파이썬은 자체적으로 배열을 제공하지 않기 때문에 numpy 사용.
  - 수치 해적용 파이선 패키지.
  - 다차원 배열 자료구조 클래스인 ndarray 지원. -> 선형대수 계산에 주로 사용.
    - a[:, [True, False, False, True]] 배열의 특정 행, 열을 골라내는 데 응용 가능할 듯.
    - a[[2, 0, 1], :] 특정 배열의 열, 행 순서를 바꿀 때도 응용 가능할 듯.
  - 파이썬 반복문에 비해 속도가 빠르며 벡터화 연산을 이용해서 간단한 코드로 복잡한 선형 대수 연산을 수행 가능.

### 넘파이 패키지 임포트

In [1]:
import numpy as np

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

- ndarray 객체와 리스트는 동일한 구조처럼 보이지만 많은 차이가 있다.
- 리스트 클래스 객체는 각각의 원소가 다른 자료형일 수 있지만 ndarray 객체는 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. (C 베이스) but 접근 실행이 빠르다.

## 백터화 연산
배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원

In [4]:
# 데이터를 모두 2배
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
#for문
answer=[]
for i in data:
    answer.append(2*i)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
# 백터화 연산
x=np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# 리스트에 적용하면? 객체의 크기가 정수배 만큼 증가.
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
a=np.array([1,2,3])
b=np.array([10,20,30])
a
b

array([10, 20, 30])

In [13]:
2*a+b

array([12, 24, 36])

In [17]:
a==2

array([False,  True, False])

In [18]:
b>10

array([False,  True,  True])

In [19]:
(a==2)&(b>10)

array([False,  True, False])

## 2차원 배열 만들기
- ndarray == N-dimensional Array
- 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성 ex. [[0, 1, 2], [3, 4, 5]]

In [21]:
c = np.array([[0,1,2],[3,4,5]])
                    #[[0,1,2],
                    # [3,4,5]]
c

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# 2차원 배열의 행과 열의 갯수확인
# 행의 갯수 : 배열 안에 있는 배열의 갯수
len(c)

2

In [26]:
# 열의 갯수 : 배열의 길이
len(c[0])

3

#### 연습 문제 1

넘파이를 사용하여 다음과 같은 행렬을 만든다.

10 20 30 40
50 60 70 80

In [28]:
F = np.array([[10,20,30,40],[50,60,70,80]])
F

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기
- 크기를 나타낼 때는 가장 바깥쪽의 리스트 길이부터 가장 안족 리스트의 길이의 순서로 표시

In [29]:
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])
# 2*3*4 array

In [30]:
# 3차원 배열의 깊이, 행, 열
# 깊이
len(d)

2

In [31]:
# 행
len(d[0])

3

In [32]:
# 열
len(d[0][0])

4

| 행 __ 열 / 깊이

## 배열의 차원과 크기 알아내기
- 더 간단한 방법 ndim, shape 속성을 이용.
- ndim : 배열의 차원
- shape : 배열의 크기 반환

In [33]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [35]:
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [36]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


## 배열의 인덱싱¶
일차원 배열의 인덱싱은 리스트의 인덱싱과 같음.

In [37]:
a = np.array([0, 1, 2, 3, 4])

In [38]:
a[2]

2

In [39]:
a[-1]

4

다차원 배열일 때 : ","를 사용하여 접근. 콤마로 구분된 차원을 axis(축)이라고도 함.

In [40]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
# 첫번째 행의 첫번째 열
a[0,0]

0

In [44]:
# 첫번째 행의 두번째 열
a[0,1]

1

In [45]:
# 마지막 행의 마지막 열
a[-1,-1]

5

## 배열 슬라이싱
배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱과 comma(,)를 함께 사용

In [46]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [50]:
 # 첫번째 행 전체
a[0, :]

array([0, 1, 2, 3])

In [52]:
# 두번째 열 전체
a[: 1]

array([[0, 1, 2, 3]])

In [53]:
# 두번째 행의 두번째 열부터 끝열까지
a[1, 1:]

array([5, 6, 7])

In [54]:
# 두번째 행까지 * 두번째 열까지
a[:2,:2]

array([[0, 1],
       [4, 5]])

#### 연습 문제 2

다음 행렬과 같은 행렬이 있다.

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [55]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [62]:
# 1
m[1,2]


7

In [63]:
# 2
m[2,4]


14

In [66]:
# 3
m[1,1:2+1]

array([6, 7])

In [68]:
# 4
m[1:2+1,2]

array([ 7, 12])

In [70]:
# 5
m[:1+1,3:]

array([[3, 4],
       [8, 9]])

## 배열 인덱싱 == 팬시 인덱싱
- 질의 기능 수행
- 배열 인덱싱에서는 [] 안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 ndarray 배열을 받을 수 있음.(==인덱스배열)
- 인덱스 배열
    - 불리언 배열 방식 : 인덱스 배열의 원소가 True, False 두 값으로만 구성, 원래 ndarray 객체의 크기와 같아야 함.
    - 정수 배열 방식 : 인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수여야 함.

불리언 배열 방식

In [71]:
# ndarray에서 짝수인 원소만 골라내려면
# 짝수인 원소에 대응하는 인덱스 값이 True이고 홀수인 원소에 대응하는 인덱스 값이 False인 인덱스 배열을 넣으면 됨.
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [75]:
# 조건문 연산
a%2 # 0, 1로

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [76]:
a%2==0 # true, false로

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [77]:
a[a%2==0] # 0인값 -> 짝수인 값

array([0, 2, 4, 6, 8])

정수 배열 방식

In [80]:
#  1차원 배열에서 홀수번째 원소만 골라내기
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [81]:
# 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음.
# 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 한다.
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [82]:
# 다차원 배열의 각 차원에 대해서도 할 수 있음.
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a[:,[True,False,True,False]] # 전체 행에서 0,2열만 출력

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

#### 콜론(:)을 사용하여 범위를 지정
start:stop:step 형식
start: 슬라이스의 시작 위치를 지정. 포함.
stop: 슬라이스의 끝 위치를 지정. 포함되지 않음.
step: 슬라이스에서 건너뛸 원소의 간격을 지정. 생략되면 기본 값인 1이 사용.

ex.
- 처음 다섯개 list[:5]
- 모든 원소를 거꾸로 list[::-1]
- 2번째 원소부터 list[1:]
- 2번째 원소부터 4번째 원소까지 list[1:4]


In [86]:
a[[2,0,1],:] # 행의 순서를 변경

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

#### 연습 문제 3
다음 행렬과 같은 배열이 있다.
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라

In [87]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
# 1
x%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
      dtype=int32)

In [91]:
x%3==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [92]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [93]:
# 2
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [97]:
x[(x%3==0) & (x%4==1)]
# & 연산자를 사용하여 불리언 값의 요소별 논리곱을 계산할 때
# !!! 조건식을 괄호로 묶어야 함. !!!

array([9])